name: manifest

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Upload Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup helm
        id: install
        uses: azure/setup-helm@v1

      - name: Build rendered-manifest.yaml
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make rendered-manifest.yaml

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload rendered-manifest.yaml
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deploy/rendered-manifest.yaml
          asset_name: rendered-manifest.yaml
          asset_content_type: application/yaml